sudo: false
language: java
jdk:
  - oraclejdk8
services:
  - docker
env:
  - MAVEN_SKIP_RC=true MAVEN_OPTS="-Xmx2560m -XX:MaxPermSize=512m"
script: "mvn clean verify -P integration-test"

after_success:
  - mvn test javadoc:javadoc
